from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class GameConfig:
    num_hexagons: int = 36
    score_threshold: float = 0.7
    enable_audio_alerts: bool = True
    volume: float = 0.5
    audio_files: dict[str, Path] = field(
        default_factory=lambda: {
            # Generated by tools/generate_alerts.py -- see that module for why
            # each alert occupies its own frequency band. These alerts double as
            # synchronisation markers for camera recordings, so which sound maps
            # to which event is analysis-relevant: a recording can only be
            # aligned by matching audio against the mapping in force when it was
            # captured.
            #
            # Three registers ship under assets/alerts/. `warm` is the default;
            # switch by pointing these paths at `mid` or `bright`, both of which
            # separate slightly better at the cost of a higher top note.
            "start_baseline": Path("assets/alerts/warm/start_baseline.wav"),
            "start_game": Path("assets/alerts/warm/start_game.wav"),
            "start_break": Path("assets/alerts/warm/start_break.wav"),
            "end_break": Path("assets/alerts/warm/end_break.wav"),
            "start_endline": Path("assets/alerts/warm/start_endline.wav"),
            "end_game": Path("assets/alerts/warm/end_game.wav"),
            # Fires after every task, so this is the most frequent sound in a
            # session and the one most often met when matching a recording.
            "task_complete": Path("assets/alerts/warm/task_complete.wav"),
        }
    )

    def get_audio_file(self, alert_type: str) -> Path | None:
        return self.audio_files.get(alert_type)

    def to_dict(self) -> dict:
        """Export configuration to dictionary."""
        return {
            "num_hexagons": self.num_hexagons,
            "score_threshold": self.score_threshold,
            "enable_audio_alerts": self.enable_audio_alerts,
            "volume": self.volume,
            "audio_files": {k: str(v) for k, v in self.audio_files.items()},
        }

    @classmethod
    def from_dict(cls, data: dict) -> GameConfig:
        """Create GameConfig from dictionary, using defaults for missing keys."""
        defaults = cls()
        audio_files_data = data.get("audio_files", {})
        # Merge provided audio files with defaults
        merged_audio_files = dict(defaults.audio_files)
        for key, path_str in audio_files_data.items():
            merged_audio_files[key] = Path(path_str)

        return cls(
            num_hexagons=data.get("num_hexagons", defaults.num_hexagons),
            score_threshold=data.get("score_threshold", defaults.score_threshold),
            enable_audio_alerts=data.get(
                "enable_audio_alerts", defaults.enable_audio_alerts
            ),
            volume=data.get("volume", defaults.volume),
            audio_files=merged_audio_files,
        )
